{
 "title": "Student Activity During Exam",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Dependency: source to target of IT Dept",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")         \r\n  |> filter(fn: (r) => r.caseId == \"IT\")\r\n  |> group(columns: [\"arc_from\", \"arc_to\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> filter(fn: (r) => r._value >= -1.0 and r._value <= 1.0)\r\n  |> keep(columns: [\"arc_label\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Dependency: source to target of Biochemistry Dept",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")         \r\n  |> filter(fn: (r) => r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"arc_from\", \"arc_to\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> filter(fn: (r) => r._value >= -1.0 and r._value <= 1.0)\r\n  |> keep(columns: [\"arc_label\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: Attend Lecture to Joined Lab",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> filter(fn: (r) => r.arc_from == \"attended_lecture\" and r.arc_to == \"joined_lab\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: Joined Lab to Check portal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> filter(fn: (r) => r.arc_from == \"joined_lab\" and r.arc_to == \"check_portal\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: Check Portal to Took Quiz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> filter(fn: (r) => r.arc_from == \"check_portal\" and r.arc_to == \"took_quiz\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: Took Quiz to Submit Assignment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> filter(fn: (r) => r.arc_from == \"took_quiz\" and r.arc_to == \"submitted_assignment\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Summary Table: Source to Target Frequency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"caseId\", \"arc_from\", \"arc_to\"])\r\n  |> sum(column: \"_value\")\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> keep(columns: [\"arc_label\", \"caseId\", \"_value\"])\r\n  |> pivot(\r\n      rowKey: [\"arc_label\"],\r\n      columnKey: [\"caseId\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Frequency over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Department: Last 60–45 min",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -60m, stop: -45m)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Department: Last 45–30 min",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -45m, stop: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Department: Last 30–15 min",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -30m, stop: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Department: Last 15 min",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dapm_std_bucket\")\r\n  |> range(start: -60m, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"IT\" or r.caseId == \"Biochemistry\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  }
 ]
}