{
 "title": "Wikipedia Event Changes",
 "time": { "from": "2025-06-30T08:31:17.000Z", "to": "2025-06-30T10:31:17.000Z" },
 "panels": [
  {
   "title": "Dependency: source to target of enwiki",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")         \r\n  |> filter(fn: (r) => r.caseId == \"enwiki\")\r\n  |> group(columns: [\"arc_from\", \"arc_to\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> filter(fn: (r) => r._value >= -1.0 and r._value <= 1.0)\r\n  |> keep(columns: [\"arc_label\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Dependency: source to target of commonswiki",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")         \r\n  |> filter(fn: (r) => r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"arc_from\", \"arc_to\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> filter(fn: (r) => r._value >= -1.0 and r._value <= 1.0)\r\n  |> keep(columns: [\"arc_label\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Dependency: source to target of ukwiki",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")         \r\n  |> filter(fn: (r) => r.caseId == \"ukwiki\")\r\n  |> group(columns: [\"arc_from\", \"arc_to\"])\r\n  |> mean()\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> filter(fn: (r) => r._value >= -1.0 and r._value <= 1.0)\r\n  |> keep(columns: [\"arc_label\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: Category to Log",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> filter(fn: (r) => r.arc_from == \"categorize\" and r.arc_to == \"log\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: Category to New",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> filter(fn: (r) => r.arc_from == \"categorize\" and r.arc_to == \"new\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: edit to category",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> filter(fn: (r) => r.arc_from == \"edit\" and r.arc_to == \"categorize\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Dependency over time: New to Log",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"dependency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> filter(fn: (r) => r.arc_from == \"new\" and r.arc_to == \"log\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Summary Table: Source to Target Frequency",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"caseId\", \"arc_from\", \"arc_to\"])\r\n  |> sum(column: \"_value\")\r\n  |> map(fn: (r) => ({ r with arc_label: r.arc_from + \" → \" + r.arc_to }))\r\n  |> keep(columns: [\"arc_label\", \"caseId\", \"_value\"])\r\n  |> pivot(\r\n      rowKey: [\"arc_label\"],\r\n      columnKey: [\"caseId\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Language: Last 60–45 min",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -60m, stop: -45m)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Language: Last 45–30 min",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -45m, stop: -30m)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Language: Last 30–15 min",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -30m, stop: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Proportions by Language: Last 15–0 min",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -15m, stop: now())\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Relative Frequency over time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"dapm_wiki_bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"heuristic_miner_arcs\")\r\n  |> filter(fn: (r) => r._field == \"frequency\")\r\n  |> filter(fn: (r) => r.caseId == \"enwiki\" or r.caseId == \"ukwiki\" or r.caseId == \"commonswiki\")\r\n  |> group(columns: [\"caseId\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}