version: "3.8"
networks:
  kafka-cluster:
    name: kafka-cluster
    external: true
    driver: bridge

services:
  zookeeper-sink:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper-sink
    restart: always
    networks:
      - kafka-cluster
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MY_ID: 1
    ports:
      - "62181:2181"

  kafka-sink:
    hostname: kafka-sink
    container_name: kafka-sink
    depends_on:
      - zookeeper-sink
    networks:
      - kafka-cluster
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    ports:
      - "9062:9062"
      - "29062:29062"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-2:2181,zookeeper-3:2181,zookeeper-sink:2181,zookeeper-ingestion:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-sink:9062,PLAINTEXT_HOST://localhost:29062
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  influxdb:
    image: influxdb:2.7.12
    container_name: influxdb
    networks:
      - kafka-cluster
    restart: always
    ports:
      - "5086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dapm_user
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=dapm
      - DOCKER_INFLUXDB_INIT_BUCKET=dapm_wiki_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dapm_token
    volumes:
      - influxdb-storage:/var/lib/influxdb2
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - kafka-cluster    # Use your actual docker network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb-storage:
  grafana-storage: