networks:
  kafka-cluster:
    name: kafka-cluster
    external: true
    driver: bridge

services:
  zookeeper-ingestion:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-ingestion
    restart: always
    networks:
      - kafka-cluster
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MY_ID: 1
    ports:
      - "12181:2181"

  kafka-ingestion:
    hostname: kafka-ingestion
    container_name: kafka-ingestion
    depends_on:
      - zookeeper-ingestion
    networks:
      - kafka-cluster
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9012:9012"
      - "29012:29012"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181,zookeeper-sink:2181,zookeeper-ingestion:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-ingestion:9012,PLAINTEXT_HOST://localhost:29012
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mongo-A:
    image: mongo:6
    container_name: mongo-A
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dapm_user
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: dapm_mapping_table
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: